=== royliwei1212/Code-Practice/src/main/resources/concept.dtd
<!ELEMENT medas (concepts,relations?)>
		<!ELEMENT concepts (concept+)>
		<!ATTLIST concepts modelPrefix CDATA #REQUIRED>
		<!ELEMENT concept (prefLabels+, properties)>
		<!ELEMENT prefLabels (prefLabel+)>

		<!ELEMENT prefLabel (#PCDATA)>
		<!ATTLIST prefLabel default CDATA #REQUIRED
				lang CDATA #REQUIRED>

		<!ELEMENT properties (property+)>
		<!ELEMENT property (value+)>
		<!ATTLIST property name CDATA #REQUIRED>
		<!ELEMENT value (#PCDATA)>


		<!ELEMENT relations (relationship_group+)>
		<!ATTLIST relations sourceModelPrefix CDATA #REQUIRED>
		<!ELEMENT relationship_group (relation+)>
		<!ATTLIST relationship_group targetModelPrefix CDATA #REQUIRED>
		<!ELEMENT relation (sourceConcept, targetConcepts)>
		<!ELEMENT sourceConcept (#PCDATA)>
		<!ATTLIST sourceConcept propertyName CDATA #REQUIRED
				propertyValue CDATA #REQUIRED>

		<!ELEMENT targetConcepts (targetConcept+)>
		<!ATTLIST targetConcepts propertyName CDATA #REQUIRED>
		<!ELEMENT targetConcept (#PCDATA)>
		<!ATTLIST targetConcept propertyValue CDATA #REQUIRED>

=== royliwei1212/Code-Practice/src/main/resources/concept.xml
<?xml version="1.0"?>
<!DOCTYPE medas SYSTEM "concept.dtd">
<medas>
	<concepts modelPrefix="ewew">
		<concept>
			<prefLabels>
				<prefLabel default="true" lang="en">ewew</prefLabel>
			</prefLabels>
			<properties>
				<property name="ewew">
					<value>ewewe</value>
					<value>fff</value>
				</property>
			</properties>
		</concept>

	</concepts>
</medas>
